### ISSUE TITLE
Implement scouring of #pics-of-homies-nothing-sexual and storage/retrieval

### ISSUE THREAD

**Issue by saigyoujisan** [Jared-Powell-WKU/Discord-Bot#1]
All that needs to happen is images of friends n family appear when /homies is run on Geoffrey

**Comment by Jared-Powell-WKU** [comment]
Hi, saigyoujisan! An early access version of /homies has been implemented in TNcord. Feel free to DM me any future feature requests, or open a new issue. Thank you!
